import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";
import { ReduxProvider } from "@/store/provider";
import BootstrapClient from "./bootstrap";

const nunito = Nunito({
	subsets: ["latin"],
	weight: "400",
	variable: "--font-nunito",
});
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="dark">
			<head>
				<meta charSet="UTF-8" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0"
				/>
				<meta name="theme-color" content="#ffce1b" />
				<link rel="icon" href="/assets/img/Krall Logo -Primary.svg" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Montserrat&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Nunito&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap"
				/>
				<link
					rel="stylesheet"
					href="assets/css/bs-theme-overrides.css"
				/>
				<link rel="stylesheet" href="assets/css/custom.compiled.css" />
				<link
					rel="stylesheet"
					href="assets/css/Hero-Clean-Reverse-images.css"
				/>
				<link
					rel="stylesheet"
					href="assets/css/Navbar-Right-Links-icons.css"
				/>
				<link rel="stylesheet" href="assets/css/styles.css" />
			</head>
			<body className={`${nunito.variable} ${geistMono.variable} bg-dark text-bg-dark`}>
        <BootstrapClient />
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
